### ISSUE TITLE
Feature Requests for SimpleHistory, SmartCopyPaste_II and SimpleBookmark

### ISSUE THREAD

**Issue by AziRizvi** [Eisa01/mpv-scripts#110]
I have some feature requests which I sincerely hope you will entertain.
The requests are for SimpleHistory, SmartCopyPaste_II and SimpleBookmark since they all share the same interface.

![mpv_ZNMFPkWZgV](https://github.com/Eisa01/mpv-scripts/assets/129892077/557af051-a9f4-488e-8b22-ed31cd95c905)

Sometimes when you have a lot of things in the history, clipboard or bookmarks, deleting them all by selecting one at a time to delete using the Delete button can be a very time consuming and painful task, how the feature I'm requesting would work is that when the history, clipboard or bookmarks are open holding down the delete key/button on the keyboard will keep deleting the entries until the delete button is released, also I would appreciate if this feature is implemented, the speed at which the entries are deleted while the button is held down can be controlled and changed.

Second thing is that one issue I often face when I am deleting entries from the history, clipboard or bookmarks is that I sometimes accidentally delete entries that I wanted to keep so a Ctrl+Z option to undelete the last deleted entry or last two deleted entries or maybe even more would be really helpful.

Once again, I would like to say thank you for all your scripts, they are a primary part of the reason why I'm able to use MPV and make life a lot easier.

**Comment by Eisa01** [comment]
Hi @AziRizvi,
The option for multiple delete is already there,

press shift while navigating, e.g.: shift + down or shift + pgdwn and so on.., you can also search for specific words then press ctrl+a.
Then for multiple delete just press shift + delete.

Some discussion for this was already in #44 , as well as in the documentation of LogManager for highlight actions.

I also just noticed shift+navigation is not mentioned in the documentation, so I need to add it.

Also for your other issue:
Since you are facing accidental delete, i recommend changing the keybind to delete to alt+delete or something.

**Comment by AziRizvi** [comment]
> Hi @AziRizvi, The option for multiple delete is already there,
> 
> press shift while navigating, e.g.: shift + down or shift + pgdwn and so on.., you can also search for specific words then press ctrl+a. Then for multiple delete just press shift + delete.
> 
> Some discussion for this was already in #44 , as well as in the documentation of LogManager for highlight actions.
> 
> I also just noticed shift+navigation is not mentioned in the documentation, so I need to add it.
> 
> Also for your other issue: Since you are facing accidental delete, i recommend changing the keybind to delete to alt+delete or something.

I didn't know it was possible to delete entries using Shift+Up/Down, thanks this solves both of my problems since now I can check and review the selected entries before deletion.
