### ISSUE TITLE
why don't you host a crowdsourced server for SmartSkip like sponsorblock does

### ISSUE THREAD

**Issue by aicynide** [Eisa01/mpv-scripts#114]
Thanks

**Comment by Eisa01** [comment]
Chapters do not get much attention, so I don't think it is worth the efforts. It is too much work for only very small audience.
This will be a new project and has to be started from scratch with parsers, etc.

Chaptersdb already failed due to very small audience, plex utilized it and is maintaining it in closed-source alternative.
https://chapterdb.plex.tv/
