### ISSUE TITLE
Smartskip: Automatic skip don't work.

### ISSUE THREAD

**Issue by glodnyy** [Eisa01/mpv-scripts#144]
i have turned on auto-skip. But everytime i turn on my anime, it doesnt skip opening automaticly. I went to config, to maybe turn on something, but nothing worked and then got default .conf file.

I need that auto-skip, it can change the way i watch anime; pls respond.

**Comment by Eisa01** [comment]
For auto skip to work, your video needs to contain chapters.

Otherwise, u need to use smart skip keybind or skip to silence keybind. (If this doesn't make sense then please read the keybinds table under SmartSkip gif)

These keybirds will skip until the end of the opening/ending, but u need to press after the opening/ending starts.

If there is an issue and SmartSkip script is crashing then share some log file.

**Comment by glodnyy** [comment]
my video contain chapters

**Comment by glodnyy** [comment]
**OKAY - SORRY I AM JUST DUMB. I DID NOT KNOW!!!!!**

First i need to select chapter by using _"shft+>"_ and then _alt+._

NOW IT IS WORKING, SORRY FOR PROBLEM.
