### ISSUE TITLE
Update/refresh history list view

### ISSUE THREAD

**Issue by fidodido48** [Eisa01/mpv-scripts#159]
Hi,
Its a great script, no doubts, but why cant i see anything past the screen height? 
I.e. I have 6 items on the list and i can go to item 7, but i cant see as the list doesnt update/refresh. One workaround is to make list font smaller to fit more items on the screen and second is to use search, but still this feel very unnatural/annoying. One should be able to explore the list up/down freely. 

Thanks for the good work, keep it up.

**Comment by AziRizvi** [comment]
You can easily explore the list up and down by using the up and down arrow keys.
![mpv_yF1kZbEIYW](https://github.com/user-attachments/assets/e58ac29b-0c8a-4e41-9e44-9182534d08cf)

**Comment by Eisa01** [comment]
This issue is happening because the displayed items size is exceeding the mpv window.

You are trying to display for example 10 items and the mpv window size can fit only 5 items.

You have multiple options in the config to resolve this:
* Either change how many items you are displaying at one time from the time the list.
* Or reduce the font size to make it able to list all items that should be displayed
* Or use trim to reduce the space each item is taking.
