### ISSUE TITLE
 SimpleHistory: Keybind for clearing history

### ISSUE THREAD

**Issue by RafeeDaBoy** [Eisa01/mpv-scripts#39]
It would be really useful if there were was keybind to clear all the items from history

**Comment by Eisa01** [comment]
For this, I think I will need to develop multiselect, it will be the best approach, e.g.: `ctrl+a` to highlight all then we can delete, add to playlist, etc.. However, it will take too much time for me to develop multi-select and give it a very natural feel. Hopefully, I will do it in future.
For now, you can clear the history by going to the log file and deleting it. It will automatically create a new log file the next time you play something.

**Comment by Eisa01** [comment]
This is done now, you can open the history list, then press `ctrl+a` to highlight all, then press `shift+del` to delete all highlighted
Or you can navigate while holding `shift`, e.g. `shift+up`, `shift+end` and it will highlight, then press `shift+del` to delete whatever is highlighted

However, because this a big update your old .log file will not be compatible, remove the old mpvHistory.log file to use the new version.
Or to migrate the log to support the new version, (make sure you backup your old .log file, just in case) open the log and usually press ctrl+h to replace the following:

replace all
` | time=`
to
` | length=0 | time=`
