### ISSUE TITLE
SimpleBookmark: Total duration for videos that are bookmarked - Feature Request

### ISSUE THREAD

**Issue by Kayizoku** [Eisa01/mpv-scripts#40]
I had the same idea as from this issue https://github.com/Eisa01/mpv-scripts/issues/34, but with a different application for SimpleBookmark script. Instead of logging time, it calculates everything that gets bookmarked and shows you the total time at the top it will take to complete the bookmarked elements. I thought it would be really neat and a nice way to see how much time it will take for you to go through the priority list with a total calculation, so you can plan your watch list more comfortably.

**Comment by Eisa01** [comment]
It seems useful, but this is currently not possible because I'm not logging the video length in the log file. 

To add that it's a lot of work, and probably all users will need to delete their log file and replace it with one that has duration.

If you have more useful use cases for the length, do let me know in this thread and if it's worth it by then, I'll see what i can do

**Comment by Kayizoku** [comment]
> It seems useful, but this is currently not possible because I'm not logging the video length in the log file.
> 
> To add that it's a lot of work, and probably all users will need to delete their log file and replace it with one that has a duration.
> 
> If you have more useful use cases for the length, do let me know in this thread and if it's worth it by then, I'll see what i can do

I see, but do you need to log time for each of the files as similar in SimpleHistory? That would definitely be a headache to get around. since you'd have to do it manually for each of the files. That's why could you not just calculate the complete duration based on the elements on the bookmarked list than at the top have a section that says: total_time = 4.24 hours or something? Instead of having a time variable for each element on the log. That's what I am thinking, but I am not so clear about the logic

**Comment by Eisa01** [comment]
> I see, but do you need to log time for each of the files as similar in SimpleHistory? That would definitely be a headache to get around. since you'd have to do it manually for each of the files. That's why could you not just calculate the complete duration based on the elements on the bookmarked list than at the top have a section that says: total_time = 4.24 hours or something?

No, that's actually possible. You can add the calculated time like SimpleHistory but I didn't add it by default to SimpleBookmark. 
In SimpleBookmark.conf change from:
`header_text=🔖 Bookmarks [%cursor/%total] %prefilter%filter%afterfilter%presearch%search%aftersearch`
to:
`header_text=🔖 Bookmarks [%cursor/%total] %prelistduration%listduration%afterlistduration%prefilter%filter%afterfilter%presearch%search%aftersearch`
That should do it.

> Basically, if I understand correctly, right now it logs time-based on how much the video is played, but we need the whole duration already from the get-go, so there should be no need to log time separately anymore, but just get the whole duration and log it to the variable the second a new element gets bookmarked. Instead of having a time variable for each element on the logger. So, the total duration for SimpleBookmark should be static and not dynamically change at all depending on what's being played. It should only need to recalculate if elements get removed from the list or if they get added. Otherwise, it should be fixed.

The dynamic time is needed as well as the static which is the video duration, it's not that hard to add but because I'm parsing the log file, if I add new additions, i need to modify the parser a little.
 I might do it actually, having the time in the log file can be quite useful

**Comment by Kayizoku** [comment]
I didn't expect my uncertain viewpoint to open doors to a possible solution. I am glad I decided to share it with you :)

It would be a really neat addition to an already awesome script no doubt.

**Comment by Kayizoku** [comment]
This is not in regards to this script but something I am creating by myself. I have tried asking in the community but no one is helpful, so if it's no trouble, I would like your help. I am writing a script to log video per line. But it's not writing to any .txt file and my log does not read any errors. I was wondering if you could help me figure out why that's happening. I would deeply appreciate the help. Only the osd_message kicks in but for some reason file:write is not working.

Here's a visual representation of what I am trying to do:

Breaking_Bad.Episode1.mkv

Breaking_Bad.Episode2.mkv

.

.

.

```
-- write to file when exiting the player or switching file
        function on_file_end()
            local message = totaltime .. "s, " .. timeloaded .. filename .. "\n"
            local file = io.open(logpath, "a")
            local lines = {}
            if not paused then totaltime = totaltime + os.clock() - lasttime end
            if file_exists(logpath) then
            for l in file:lines() do
                if not l:find(message "%a", 1, true) then
                lines[#lines+1] = l
                file:write(message)
                file:close()
                mp.osd_message("test")
            end
        end  
    end
end
```

**Comment by Kayizoku** [comment]
This is not in regards to this script but something I am creating. I have tried asking in the community but no one is very helpful so far, so if it's no trouble, I would like your help and if you cannot, just tell me and I will delete this comment. I am writing a script to log video per line. But it's not writing to any .txt file and my log does not read any errors. I was wondering if you could help me figure out why that's happening. I would deeply appreciate the help. Only the osd_message kicks in but for some reason file:write is not working. If you need the whole code, just tell me, but for now, I think the issue lies in this snippet.

Here's a visual representation of what I am trying to do:

Breaking_Bad.Episode1.mkv

Breaking_Bad.Episode2.mkv

.

.

.

```
-- write to file when exiting the player or switching file
        function on_file_end()
            local message = totaltime .. "s, " .. timeloaded .. filename .. "\n"
            local file = io.open(logpath, "a")
            local lines = {}
            if not paused then totaltime = totaltime + os.clock() - lasttime end
            if file_exists(logpath) then
            for l in file:lines() do
                if not l:find(message "%a", 1, true) then
                lines[#lines+1] = l
                file:write(message)
            end
        end  
        file:close()
        mp.osd_message("test")
    end
end
```

**Comment by Eisa01** [comment]
I suggest trying harder, not losing hope, and you will eventually get it. 
This is how programming skills are developed.

Also, I'll be deleting both comments in approximately 3 days to keep things related.
For such stuff, contact me via email which can be found in my github profile. (I may be slow to respond)

**Comment by Kayizoku** [comment]
> I suggest trying harder, not losing hope, and you will eventually get it. This is how programming skills are developed.
> 
> For such stuff, contact me via email which can be found in my github profile. (I may be slow to respond)

Thank you for your words of encouragement, but I still haven't been able to get it and I really need this.

**Comment by Eisa01** [comment]
Hi, it is done now as part of the new release. https://github.com/Eisa01/mpv-scripts/releases
However, you will need to delete your old log file and use the new one generated from the new script.

Modify the conf file for SimpleBookmark
The option to show the total for the remaining time for bookmarks in the header:
`header_text=🔖 Bookmarks [%cursor%/%total%]%prehighlight%%highlight%%afterhighlight%%prelistremaining%%listremaining%%afterlistremaining%%prefilter%%filter%%afterfilter%%presort%%sort%%aftersort%%presearch%%search%%aftersearch%`

You can also change the items in the list to show remaining time instead of reached time if you want:
`text_time_type=remaining`
