### ISSUE TITLE
SimpleHistory: Auto Delete logs if File(s) Does not Exist

### ISSUE THREAD

**Issue by Cananbolt** [Eisa01/mpv-scripts#56]
Would it be possible to auto-delete logs if the file is not in your system? It may be best if it was based on the file path, as if it is based on media-name or file-name it could cause problems.

For example...
Say there was a file in C:\Users\Me\Videos, and I delete/move the file, then when I start MPV up again that log will be deleted.

However, if that same file was in another directory C:\Users\Me\Downloads, it would run normally with no auto-deletion.

**Comment by Eisa01** [comment]
Why not just run add the path to blacklist if you don't want it to store videos from `C:\Users\Me\Videos`?
And if its a temporary thing and you don't want to blacklist the path, you can run incognito mode so that it doesn't store this specific video<html>
<body>


ctrl+H | history-incognito-mode | Triggeres a customizable incognito mode that stops saving history. To resume saving history press ctrl+H again
-- | -- | --



</body>
</html>

**Comment by Cananbolt** [comment]
My apologies, I wasn't clear with my request. I do want to log the files; however, at the end of a tv series I finished watching, I would delete all the media files from my pc. Then when I go back to mpv, it would still show the logs for the show I've finished. If I were to select it, it would then say, "File Doesn't Exist." Then, I would have to manually delete the files by going to the "all protocol" in the script, "Ctrl+f" to find the series I watched, "Ctrl+a" to select all, and then finally "Ctrl+Del" to delete all of them. I wanted to know if there was a way to skip that entire process and have the script automatically delete logs of a media file if it is not on the system anymore.

**Comment by Eisa01** [comment]
Even if it's possible, I think it will be very heavy on mpv.
In order to do it, I have to loop through all the history when mpv launches and check the paths of all logged items. Once an item is not found it will delete it. 
Imagine this process happening every time you launch mpv, it seems very heavy, because this check must happen at every launch event for mpv.

**Comment by Cananbolt** [comment]
I understand, it definitely does seem like it would be heavy on mpv. I just thought it would be very convenient to have.

**Comment by Eisa01** [comment]
I'll see if there is a way around it when populating the items, first time for LogManager, but currently I am too busy to add new features. I'll close it for now, but might test it in the future and add it if it didn't cause issues.
Thanks for throwing the idea.

**Comment by Cananbolt** [comment]
No problem, thanks again for considering it
